# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umujyi', models.CharField(max_length=30)),
                ('umurenge', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
